#ifndef CALIBRATION_TABLES_GEO_BP_H
#define CALIBRATION_TABLES_GEO_BP_H

/* GEO_BP: VDAC_ref_BP, AMux_ADC=1. Se calibra siempre si el componente existe. */

#ifndef CAL_TARGET_GEO_BP_MV
#define CAL_TARGET_GEO_BP_MV 0L
#endif
#define CAL_TARGET_COUNTS_GEO_BP (CAL_TARGET_GEO_BP_MV * CAL_TARGET_1V_COUNTS / 1000L)

#define CAL_DIRECTION_GEO_BP 1

#ifndef CAL_ADELANTO_GEO_BP_MV
#define CAL_ADELANTO_GEO_BP_MV 2500L
#endif
#define CAL_DAC_CENTER_GEO_BP ((uint8)(CAL_ADELANTO_GEO_BP_MV / CAL_VDAC8_MV_PER_LSB))

#define CAL_DAC_MAX_CHANGE_GEO_BP 255u

#ifndef CAL_PI_GAIN_GEO_BP_X1000
#define CAL_PI_GAIN_GEO_BP_X1000 1000L
#endif

/* Delta_BP usado: tres codigos, con holgura sobre el piso de un codigo. */
#ifndef CAL_PI_DEADBAND_GEO_BP_DAC_CODES
#define CAL_PI_DEADBAND_GEO_BP_DAC_CODES 3L
#endif

/* P=100e-6, I=500e-6. */
#define CAL_PI_KP_NUM_GEO_BP 1L
#define CAL_PI_KP_DIV_GEO_BP 10000L
#define CAL_PI_KI_NUM_GEO_BP 1L
#define CAL_PI_KI_DIV_GEO_BP 2000L

#ifndef CAL_PI_LOCK_SAMPLES_GEO_BP
#define CAL_PI_LOCK_SAMPLES_GEO_BP 1024u
#endif

#ifndef CAL_PI_SETTLE_SAMPLES_GEO_BP
#define CAL_PI_SETTLE_SAMPLES_GEO_BP 512u
#endif

#ifndef CAL_PI_TIMEOUT_SAMPLES_GEO_BP
#define CAL_PI_TIMEOUT_SAMPLES_GEO_BP 45000u
#endif

#ifndef CAL_PI_REFINE_ENABLE_GEO_BP
#define CAL_PI_REFINE_ENABLE_GEO_BP 1u
#endif

#ifndef CAL_PI_REFINE_SETTLE_SAMPLES_GEO_BP
#define CAL_PI_REFINE_SETTLE_SAMPLES_GEO_BP 1024u
#endif

#endif
