#ifndef CALIBRATION_TABLES_LEGACY_BISECTION_H
#define CALIBRATION_TABLES_LEGACY_BISECTION_H

/* Parametros historicos de busqueda binaria/verify/realcheck.
 * No se incluyen desde el firmware activo. Quedan aca para poder consultar o
 * reconstruir la calibracion vieja sin mezclarla con el PI vigente. */

#ifndef ADC_DEFAULT_SRATE
#define ADC_DEFAULT_SRATE 3000u
#endif

#ifndef CAL_SETTLE_FACTOR
#define CAL_SETTLE_FACTOR 3u
#endif

#ifndef CAL_SETTLE_FACTOR_DEN
#define CAL_SETTLE_FACTOR_DEN 1u
#endif

#define CAL_LEGACY_SETTLE_SAMPLES_FROM_US(us) \
    ((uint16)((((uint32)(us) * (uint32)ADC_DEFAULT_SRATE * (uint32)CAL_SETTLE_FACTOR) + \
               ((uint32)CAL_SETTLE_FACTOR_DEN * 1000000UL) - 1UL) / \
              ((uint32)CAL_SETTLE_FACTOR_DEN * 1000000UL)))

#define CAL_LEGACY_SETTLE_SAMPLES_FROM_MS(ms) \
    CAL_LEGACY_SETTLE_SAMPLES_FROM_US(((uint32)(ms) * 1000UL))

#define CAL_LEGACY_AVG_WINDOW_MAX 64u
#define CAL_LEGACY_BEST_CANDIDATE_COUNT 4u
#define CAL_LEGACY_VISIT_HISTORY_COUNT  8u

#define CAL_LEGACY_PROBE_STEP_GEO_PGA 32u
#define CAL_LEGACY_MAX_ITER_GEO_PGA   16u
#define CAL_LEGACY_TOL_COUNTS_GEO_PGA (100L * CAL_TARGET_1V_COUNTS / 1000L)
#define CAL_LEGACY_DEADBAND_COUNTS_GEO_PGA CAL_LEGACY_TOL_COUNTS_GEO_PGA
#define CAL_LEGACY_VERIFY_SETTLE_SAMPLES_GEO_PGA CAL_LEGACY_SETTLE_SAMPLES_FROM_MS(220u)
#define CAL_LEGACY_AVG_N_GEO_PGA 64u
#define CAL_LEGACY_AVG_WINDOW_COUNT_GEO_PGA 16u
#define CAL_LEGACY_AVG_MAX_SAMPLES_GEO_PGA 2048u
#define CAL_LEGACY_VERIFY_AVG_MAX_SAMPLES_GEO_PGA 4096u
#define CAL_LEGACY_SAT_COUNTS_GEO_PGA 120000L

#define CAL_LEGACY_PROBE_STEP_GEO_BP 32u
#define CAL_LEGACY_MAX_ITER_GEO_BP   16u
#define CAL_LEGACY_TOL_COUNTS_GEO_BP (100L * CAL_TARGET_1V_COUNTS / 1000L)
#define CAL_LEGACY_DEADBAND_COUNTS_GEO_BP CAL_LEGACY_TOL_COUNTS_GEO_BP
#define CAL_LEGACY_VERIFY_SETTLE_SAMPLES_GEO_BP CAL_LEGACY_SETTLE_SAMPLES_FROM_US(100u)
#define CAL_LEGACY_AVG_N_GEO_BP 64u
#define CAL_LEGACY_AVG_WINDOW_COUNT_GEO_BP 16u
#define CAL_LEGACY_AVG_MAX_SAMPLES_GEO_BP 2048u
#define CAL_LEGACY_VERIFY_AVG_MAX_SAMPLES_GEO_BP 4096u
#define CAL_LEGACY_SAT_COUNTS_GEO_BP 120000L

#define CAL_LEGACY_PROBE_STEP_GEO_ADDER 32u
#define CAL_LEGACY_MAX_ITER_GEO_ADDER   16u
#define CAL_LEGACY_TOL_COUNTS_GEO_ADDER (100L * CAL_TARGET_1V_COUNTS / 1000L)
#define CAL_LEGACY_DEADBAND_COUNTS_GEO_ADDER CAL_LEGACY_TOL_COUNTS_GEO_ADDER
#define CAL_LEGACY_VERIFY_SETTLE_SAMPLES_GEO_ADDER CAL_LEGACY_SETTLE_SAMPLES_FROM_US(200u)
#define CAL_LEGACY_AVG_N_GEO_ADDER 64u
#define CAL_LEGACY_AVG_WINDOW_COUNT_GEO_ADDER 16u
#define CAL_LEGACY_AVG_MAX_SAMPLES_GEO_ADDER 2048u
#define CAL_LEGACY_VERIFY_AVG_MAX_SAMPLES_GEO_ADDER 4096u
#define CAL_LEGACY_SAT_COUNTS_GEO_ADDER 120000L

#define CAL_LEGACY_PROBE_STEP_GEO_LP 32u
#define CAL_LEGACY_MAX_ITER_GEO_LP   16u
#define CAL_LEGACY_TOL_COUNTS_GEO_LP (100L * CAL_TARGET_1V_COUNTS / 1000L)
#define CAL_LEGACY_DEADBAND_COUNTS_GEO_LP CAL_LEGACY_TOL_COUNTS_GEO_LP
#define CAL_LEGACY_VERIFY_SETTLE_SAMPLES_GEO_LP CAL_LEGACY_SETTLE_SAMPLES_FROM_MS(6u)
#define CAL_LEGACY_AVG_N_GEO_LP 64u
#define CAL_LEGACY_AVG_WINDOW_COUNT_GEO_LP 16u
#define CAL_LEGACY_AVG_MAX_SAMPLES_GEO_LP 2048u
#define CAL_LEGACY_VERIFY_AVG_MAX_SAMPLES_GEO_LP 4096u
#define CAL_LEGACY_SAT_COUNTS_GEO_LP 120000L

#define CAL_LEGACY_PROBE_STEP_HAMMER_PGA 32u
#define CAL_LEGACY_MAX_ITER_HAMMER_PGA 16u
#define CAL_LEGACY_TOL_COUNTS_HAMMER_PGA 6000L
#define CAL_LEGACY_DEADBAND_COUNTS_HAMMER_PGA CAL_LEGACY_TOL_COUNTS_HAMMER_PGA
#define CAL_LEGACY_VERIFY_SETTLE_SAMPLES_HAMMER_PGA 900u
#define CAL_LEGACY_SAT_COUNTS_HAMMER_PGA 120000L

#define CAL_LEGACY_PROBE_STEP_HAMMER_LP 32u
#define CAL_LEGACY_MAX_ITER_HAMMER_LP 16u
#define CAL_LEGACY_TOL_COUNTS_HAMMER_LP 6000L
#define CAL_LEGACY_DEADBAND_COUNTS_HAMMER_LP CAL_LEGACY_TOL_COUNTS_HAMMER_LP
#define CAL_LEGACY_VERIFY_SETTLE_SAMPLES_HAMMER_LP 1200u
#define CAL_LEGACY_SAT_COUNTS_HAMMER_LP 120000L

#define CAL_LEGACY_REALCHECK_ENABLE 1u
#define CAL_LEGACY_REALCHECK_TOL_COUNTS (100L * CAL_TARGET_1V_COUNTS / 1000L)
#define CAL_LEGACY_REALCHECK_NUDGE_STEP 1u
#define CAL_LEGACY_REALCHECK_MAX_NUDGES 3u
#define CAL_LEGACY_REALCHECK_AVG_N 64u
#define CAL_LEGACY_REALCHECK_AVG_WINDOW_COUNT 64u
#define CAL_LEGACY_REALCHECK_AVG_MAX_SAMPLES 8192u
#define CAL_LEGACY_REALCHECK_AVG_SETTLE_TOL 10L
#define CAL_LEGACY_REALCHECK_AVG_STABLE_STREAK 3u

/* Bypass historico de GEO_BP. No existe en los headers activos porque BP debe
 * calibrarse siempre. */
#define CAL_LEGACY_GEO_BP_SKIP 0u

#endif
