#ifndef CALIBRATION_TABLES_HAMMER_LP_H
#define CALIBRATION_TABLES_HAMMER_LP_H

/* HAMMER_LP: VDAC_LP, AMux_ADC=1. */

#ifndef CAL_TARGET_HAMMER_LP_MV
#define CAL_TARGET_HAMMER_LP_MV 3500L
#endif
#define CAL_TARGET_HAMMER_LP_COUNTS (CAL_TARGET_HAMMER_LP_MV * CAL_TARGET_1V_COUNTS / 1000L)

#define CAL_DIRECTION_HAMMER_LP 1

#ifndef CAL_ADELANTO_HAMMER_LP_MV
#define CAL_ADELANTO_HAMMER_LP_MV 1280L
#endif
#define CAL_DAC_CENTER_HAMMER_LP ((uint8)(CAL_ADELANTO_HAMMER_LP_MV / CAL_VDAC8_MV_PER_LSB))

#define CAL_DAC_MAX_CHANGE_HAMMER_LP 255u

#ifndef CAL_PI_GAIN_HAMMER_LP_X1000
#define CAL_PI_GAIN_HAMMER_LP_X1000 6000L
#endif

/* P=100e-6, I=500e-6. */
#define CAL_PI_KP_NUM_HAMMER_LP 1L
#define CAL_PI_KP_DIV_HAMMER_LP 10000L
#define CAL_PI_KI_NUM_HAMMER_LP 1L
#define CAL_PI_KI_DIV_HAMMER_LP 2000L

#ifndef CAL_PI_LOCK_SAMPLES_HAMMER_LP
#define CAL_PI_LOCK_SAMPLES_HAMMER_LP 1024u
#endif

#ifndef CAL_PI_SETTLE_SAMPLES_HAMMER_LP
#define CAL_PI_SETTLE_SAMPLES_HAMMER_LP 512u
#endif

#ifndef CAL_PI_TIMEOUT_SAMPLES_HAMMER_LP
#define CAL_PI_TIMEOUT_SAMPLES_HAMMER_LP 45000u
#endif

#ifndef CAL_PI_REFINE_ENABLE_HAMMER_LP
#define CAL_PI_REFINE_ENABLE_HAMMER_LP 1u
#endif

#ifndef CAL_PI_REFINE_SETTLE_SAMPLES_HAMMER_LP
#define CAL_PI_REFINE_SETTLE_SAMPLES_HAMMER_LP 2048u
#endif

#endif
