#ifndef CALIBRATION_TABLES_GEO_ADDER_H
#define CALIBRATION_TABLES_GEO_ADDER_H

/* GEO_ADDER: VDAC_Ref_Adder, AMux_ADC=2. */

#ifndef CAL_TARGET_GEO_ADDER_MV
#define CAL_TARGET_GEO_ADDER_MV 0L
#endif
#define CAL_TARGET_COUNTS_GEO_ADDER (CAL_TARGET_GEO_ADDER_MV * CAL_TARGET_1V_COUNTS / 1000L)

#define CAL_DIRECTION_GEO_ADDER 1

#ifndef CAL_ADELANTO_GEO_ADDER_MV
#define CAL_ADELANTO_GEO_ADDER_MV 2500L
#endif
#define CAL_DAC_CENTER_GEO_ADDER ((uint8)(CAL_ADELANTO_GEO_ADDER_MV / CAL_VDAC8_MV_PER_LSB))

#define CAL_DAC_MAX_CHANGE_GEO_ADDER 255u

#ifndef CAL_PI_GAIN_GEO_ADDER_X1000
#define CAL_PI_GAIN_GEO_ADDER_X1000 3000L
#endif

/* P=100e-6, I=500e-6. */
#define CAL_PI_KP_NUM_GEO_ADDER 1L
#define CAL_PI_KP_DIV_GEO_ADDER 10000L
#define CAL_PI_KI_NUM_GEO_ADDER 1L
#define CAL_PI_KI_DIV_GEO_ADDER 2000L

#ifndef CAL_PI_LOCK_SAMPLES_GEO_ADDER
#define CAL_PI_LOCK_SAMPLES_GEO_ADDER 512u
#endif

#ifndef CAL_PI_SETTLE_SAMPLES_GEO_ADDER
#define CAL_PI_SETTLE_SAMPLES_GEO_ADDER 512u
#endif

#ifndef CAL_PI_TIMEOUT_SAMPLES_GEO_ADDER
#define CAL_PI_TIMEOUT_SAMPLES_GEO_ADDER CAL_PI_DEFAULT_TIMEOUT_SAMPLES
#endif

#ifndef CAL_PI_REFINE_ENABLE_GEO_ADDER
#define CAL_PI_REFINE_ENABLE_GEO_ADDER 1u
#endif

#ifndef CAL_PI_REFINE_SETTLE_SAMPLES_GEO_ADDER
#define CAL_PI_REFINE_SETTLE_SAMPLES_GEO_ADDER 1024u
#endif

#endif
