/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SEo_aliases.h"
#include "SEo.h"
#include "OPAref.h"
#include "ADC.h"
#include "OPAadder.h"
#include "PGAgain.h"
#include "BPp_aliases.h"
#include "BPp.h"
#include "VDACo_aliases.h"
#include "VDACo.h"
#include "ADDERp_aliases.h"
#include "ADDERp.h"
#include "REF_aliases.h"
#include "REF.h"
#include "BPm_aliases.h"
#include "BPm.h"
#include "OPAbp.h"
#include "PGAvdac.h"
#include "INn_aliases.h"
#include "INn.h"
#include "INp_aliases.h"
#include "INp.h"
#include "PGAn.h"
#include "PGAp.h"
#include "VDAC.h"
#include "isr_DelSig.h"
#include "SYNC_IN_aliases.h"
#include "SYNC_IN.h"
#include "BPo_aliases.h"
#include "BPo.h"
#include "ADDERm_aliases.h"
#include "ADDERm.h"
#include "ADDERo_aliases.h"
#include "ADDERo.h"
#include "OPAlp.h"
#include "LPp_aliases.h"
#include "LPp.h"
#include "LPm_aliases.h"
#include "LPm.h"
#include "LPo_aliases.h"
#include "LPo.h"
#include "LPF_2.h"
#include "LPF_1.h"
#include "LED_aliases.h"
#include "LED.h"
#include "Timer.h"
#include "isr_Timer.h"
#include "isr_SyncIn.h"
#include "UART.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

