/*******************************************************************************
* File Name: cyfitter_cfg.h
* 
* PSoC Creator  4.4
*
* Description:
* This file provides basic startup and mux configuration settings
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef CYFITTER_CFG_H
#define CYFITTER_CFG_H

#include "cytypes.h"

extern void cyfitter_cfg(void);

/* Analog Set/Unset methods */
extern void SetAnalogRoutingPumps(uint8 enabled);
extern void MuxIn_CYAMUXSIDE_A_Set(uint8 channel);
extern void MuxIn_CYAMUXSIDE_A_Unset(uint8 channel);
extern void MuxIn_CYAMUXSIDE_B_Set(uint8 channel);
extern void MuxIn_CYAMUXSIDE_B_Unset(uint8 channel);
/* MuxIn_CYAMUXSIDE_B__addrTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern uint8 CYXDATA * const CYCODE MuxIn_CYAMUXSIDE_B__addrTable[4];
/* MuxIn_CYAMUXSIDE_B__maskTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern const uint8 CYCODE MuxIn_CYAMUXSIDE_B__maskTable[4];
extern void MuxOut_CYAMUXSIDE_A_Set(uint8 channel);
extern void MuxOut_CYAMUXSIDE_A_Unset(uint8 channel);
/* MuxOut_CYAMUXSIDE_A__addrTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern uint8 CYXDATA * const CYCODE MuxOut_CYAMUXSIDE_A__addrTable[4];
/* MuxOut_CYAMUXSIDE_A__maskTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern const uint8 CYCODE MuxOut_CYAMUXSIDE_A__maskTable[4];
extern void MuxOut_CYAMUXSIDE_B_Set(uint8 channel);
extern void MuxOut_CYAMUXSIDE_B_Unset(uint8 channel);


#endif /* CYFITTER_CFG_H */

/*[]*/
