/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "WaveDAC.h"
#include "Clock_Wave.h"
#include "DiffOut_p_aliases.h"
#include "DiffOut_p.h"
#include "TIAOut_n_aliases.h"
#include "TIAOut_n.h"
#include "TIAInI_n_aliases.h"
#include "TIAInI_n.h"
#include "TIAOut_p_aliases.h"
#include "TIAOut_p.h"
#include "TIAInI_p_aliases.h"
#include "TIAInI_p.h"
#include "TIA_n.h"
#include "TIA_p.h"
#include "DiffInI_p_aliases.h"
#include "DiffInI_p.h"
#include "DiffOut_n_aliases.h"
#include "DiffOut_n.h"
#include "DiffInI_n_aliases.h"
#include "DiffInI_n.h"
#include "DiffInNI_n_aliases.h"
#include "DiffInNI_n.h"
#include "ADC_n_aliases.h"
#include "ADC_n.h"
#include "OpaDiff_n.h"
#include "OpaDiff_p.h"
#include "DiffInNI_p_aliases.h"
#include "DiffInNI_p.h"
#include "Comun_aliases.h"
#include "Comun.h"
#include "PGAout_p_aliases.h"
#include "PGAout_p.h"
#include "PGAout_n_aliases.h"
#include "PGAout_n.h"
#include "WRef_aliases.h"
#include "WRef.h"
#include "In_n_aliases.h"
#include "In_n.h"
#include "In_p_aliases.h"
#include "In_p.h"
#include "PGA_n.h"
#include "PGA_p.h"
#include "WaveGenerator_aliases.h"
#include "WaveGenerator.h"
#include "Opa_ref.h"
#include "Opa_comun.h"
#include "ADC_p_aliases.h"
#include "ADC_p.h"
#include "isr_boton.h"
#include "Clock_Debouncer.h"
#include "boton_aliases.h"
#include "boton.h"
#include "WaveDAC_Wave1_DMA_dma.h"
#include "WaveDAC_Wave2_DMA_dma.h"
#include "WaveDAC_VDAC8.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

