/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "INA_PGA_p.h"
#include "INA_PGA_m.h"
#include "INA_p_aliases.h"
#include "INA_p.h"
#include "INA_m_aliases.h"
#include "INA_m.h"
#include "INA_middle_p_aliases.h"
#include "INA_middle_p.h"
#include "INA_middle_m_aliases.h"
#include "INA_middle_m.h"
#include "INA_Opamp.h"
#include "INA_out_aliases.h"
#include "INA_out.h"
#include "Pin_5_aliases.h"
#include "Pin_5.h"
#include "Pin_6_aliases.h"
#include "Pin_6.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

