#ifndef CALIBRATION_TABLES_GEO_SUM_H
#define CALIBRATION_TABLES_GEO_SUM_H

/* GEO_SUM: VDAC_Ref_Sum, AMux_ADC=2. */

#ifndef CAL_TARGET_GEO_SUM_MV
#define CAL_TARGET_GEO_SUM_MV 0L
#endif
#define CAL_TARGET_COUNTS_GEO_SUM (CAL_TARGET_GEO_SUM_MV * CAL_TARGET_1V_COUNTS / 1000L)

#define CAL_DIRECTION_GEO_SUM 1

#ifndef CAL_ADELANTO_GEO_SUM_MV
#define CAL_ADELANTO_GEO_SUM_MV 2500L
#endif
#define CAL_DAC_CENTER_GEO_SUM ((uint8)(CAL_ADELANTO_GEO_SUM_MV / CAL_VDAC8_MV_PER_LSB))

#define CAL_DAC_MAX_CHANGE_GEO_SUM 255u

#ifndef CAL_PI_GAIN_GEO_SUM_X1000
#define CAL_PI_GAIN_GEO_SUM_X1000 7890L
#endif

#ifndef CAL_PI_DEADBAND_GEO_SUM_DAC_CODES
#define CAL_PI_DEADBAND_GEO_SUM_DAC_CODES 10L
#endif

/* P=100e-6, I=500e-6. */
#define CAL_PI_KP_NUM_GEO_SUM 1L
#define CAL_PI_KP_DIV_GEO_SUM 10000L
#define CAL_PI_KI_NUM_GEO_SUM 1L
#define CAL_PI_KI_DIV_GEO_SUM 2000L

#ifndef CAL_PI_LOCK_SAMPLES_GEO_SUM
#define CAL_PI_LOCK_SAMPLES_GEO_SUM 512u
#endif

#ifndef CAL_PI_SETTLE_SAMPLES_GEO_SUM
#define CAL_PI_SETTLE_SAMPLES_GEO_SUM 512u
#endif

#ifndef CAL_PI_TIMEOUT_SAMPLES_GEO_SUM
#define CAL_PI_TIMEOUT_SAMPLES_GEO_SUM CAL_PI_DEFAULT_TIMEOUT_SAMPLES
#endif

#ifndef CAL_PI_REFINE_ENABLE_GEO_SUM
#define CAL_PI_REFINE_ENABLE_GEO_SUM 1u
#endif

#ifndef CAL_PI_REFINE_SETTLE_SAMPLES_GEO_SUM
#define CAL_PI_REFINE_SETTLE_SAMPLES_GEO_SUM 1024u
#endif

#endif
